# cloud-config 
package_update: true
packages:
  - docker.io
  
runcmd:
  - systemctl enable docker
  - systemctl start docker

# Pull image from Docker Hub

  - docker pull user/webapp:1.0

# Run container
  - docker run -d -p 80:80 --name webapp user/webapp:1.0
